# Properties of Dot Product - Lab

## Introduction

In this lab we shall look at some interesting properties of a Dot product type matrix multiplication. Understanding these properties will become useful as we move forward with machine learning advanced linear algebra. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - Matrices multiplication is distributive
### Prove that A.(B+C)=A.B+A.C

In [11]:
# Your code here
import numpy as np
import random

def rand_matrix(d1, d2):
    A = np.zeros((d1,d2))
    B = np.zeros((d1,d2))
    C = np.zeros((d1,d2))
    for i in range(d1):
        for j in range(d2):
            A[i][j] = random.randrange(1,10)
            B[i][j] = random.randrange(1,10)
            C[i][j] = random.randrange(1,10)
    return A, B, C

A, B, C = rand_matrix(3,3)
print(A)
print('\n',B)
print('\n',C)

[[9. 7. 5.]
 [5. 6. 5.]
 [9. 6. 1.]]

 [[1. 8. 1.]
 [1. 5. 9.]
 [5. 6. 3.]]

 [[7. 8. 3.]
 [9. 3. 1.]
 [6. 9. 2.]]


In [17]:
A.dot(B+C) == A.dot(B)+A.dot(C)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Associative Property - Matrices multiplication is associative
### Prove that A.(B.C)=(A.B).C

In [18]:
# Your code here 
A.dot(B.dot(C)) == (A.dot(B)).dot(C)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Commutative Property - Matrix multiplication is NOT commutative
### Prove that for matrices, A.B ≠ B.A

In [20]:
# Your code here 
A.dot(B) == B.dot(A)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors, x<sup>T</sup> . y = y<sup>T</sup> . x
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [22]:
# Your code here 
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

a.T.dot(b) == b.T.dot(a)

True

#### and finally 
## Simplification of the matrix product
### Prove that  (A.B)<sup>T</sup> = B<sup>T</sup> . A<sup>T</sup>

In [24]:
# Your code here 
(A.dot(B)).T == B.T.dot(A.T)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Summary 

So now we have seen enough matrix algebra to help us solve a problem of linear equations as we saw earlier in this section. We shall see how to do this next. 